PREFIX fml: <https://fairmodels.org/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?algorithm ?algorithmType
WHERE {
    ?model rdf:type fml:Model.
    ?model fml:contains_algorithm ?algorithm.
    ?algorithm rdf:type ?algorithmType.
}